- .gitignore
- README.md
- circle.yml
- examples/ad/AD.hs
- stack.yaml
updated readme to point to org repo, switch over from stack nightly to lts 10.2
> updated readme to point to org repo, switch over from stack nightly

- docs/api-design.md
I've worked through a couple of prototypes and these are my thoughts around the best way to proceed. Feel free to inline comments, ask questions, and point out things that I'm missing.
> some notes on the api

- core/src/generic/Torch/Core/Tensor/Static/DoubleMath.hs
- core/src/generic/Torch/Core/Tensor/Static/Long.hs
I've implemented a toy example for a Lasso linear model and a coordinate descent method and during the implementation I found I needed some slicing utilities.
Does this sound okay?
> Add slicing utilities

- core/src/generic/Torch/Core/Tensor/Static/DoubleMath.hs
- core/src/generic/Torch/Core/Tensor/Static/Long.hs
- examples/lasso/Lasso.hs
This must be merged after #70 .
It would be nice if anyone with knowledge on Coordinate Descent methods would review that code, I think there's something missing for it to be fully working. 
FISTA is reliable and works as expected. 
All in all, this is a very successful example of the implementation of two state of the art methods in machine learning in haskell, which I think is a very nice precedent for hasktorch.
> Lasso example

- core/src/generic/Torch/Core/Tensor/Static/DoubleMath.hs
This was left out in a previous commit because I didn't know about reification and didn't get right the `indices` TLS tensor. If everyone's fine with this, one less function to do.
Before merging I should probably add some tests, just wanted to know your first impressions on this one.
> Add `tds_getIndicesTensor` to retrieve any number of rows/columns

- examples/linear-regression/boston.py
Simple one layer NN for housing price prediction using PyTorch.
> Initial linear regression code.

- .cabal.project.freeze/8.2.2
- .cabal.project.freeze/8.4.2
- .cabal.project.freeze/8.4.3
- build.nix
- nix-releases/ghc844-mkl-cpu.nix
- nix-releases/ghc861-mkl-cpu.nix
- shell.nix
- Sam's nix support for building aten
- modify `build-aten.sh` script to allow gcc-8 and gcc-9
> Project build updates

- DEVELOPERS.md
- Makefile
- cabal.project.freeze
Issues in building, across three machines (two PCs and a remote server) recorded, along with solutions. Everything's in DEVELOPERS.md. The issues have been machine-specific, so my solutions to them have mostly been "If X issue with Y build script, then here is how to build from scratch"
> Build Issues Recorded

- .circleci/config.yml
- deps/get-deps.sh
- setenv
- setup-cabal.sh
- stack.yaml
* Update lts
* Fix setenv's bug
* Fix get-deps.sh not to use python-2
> Update lts-version to 13.30

- examples/static_xor_mlp/Main.hs
- hasktorch/hasktorch.cabal
- hasktorch/src/Torch/DType.hs
- hasktorch/src/Torch/Functions.hs
- hasktorch/src/Torch/Functions/Native.hs
- hasktorch/src/Torch/Static.hs
- hasktorch/src/Torch/Static/Native.hs
- hasktorch/test/doctests.hs
I want to think adding static typed tensor practically.
At first, add template codes of static typed functions, but the definitions of some/many functions are wrong.
Next, add test for the functions and think next steps.
> Add template codes to develop static-typed-functions

- libtorch-ffi/libtorch-ffi.cabal
- nix/nixpkgs.json
- nix/shared.nix
opening this PR to run the code against CI....
> fix/nix macos and unzip, too

- .gitignore
- examples/.hie-wrapper.sh
- examples/static_xor_mlp/Main.hs
- hasktorch/src/Torch/Static.hs
- hasktorch/src/Torch/Static/Factories.hs
- hasktorch/src/Torch/Static/Native.hs
- hasktorch/test/StaticSpec.hs
> clean up and improve static xor example

- .github/workflows/cabal-linux.yml
- .github/workflows/nix-linux.yml
- .github/workflows/nix-macos.yml
- .github/workflows/stack-linux.yml
- setup-cabal.sh
- stack.yaml
This PR tries to fix the setup-error of github-actions(https://github.com/hasktorch/hasktorch/commit/99ec5bd9606dfc7613b352482f74bc857f9aed59/checks ).
> Fix installation of stack on CI and retry nix-setup

- examples/README.md
- examples/gaussian-process/Main.hs
- examples/gaussian-process/README.md
- examples/minimal-text-example/Hello.hs
- examples/optimizers/README.md
- examples/regression/README.md
- examples/serialization/README.md
- examples/vae/Main.hs
- examples/vae/README.md
- examples/xor-mlp/Main.hs
- examples/xor-mlp/README.md
- Update top-level README for example with new examples
- Clean up tensor-blindness of gaussian process example
- Add READMEs for linear regression and gaussian process
- Add placeholder READMEs in other examples
> Tidy up examples

- examples/static-transformer/Main.hs
- hasktorch/src/Torch/Static.hs
- hasktorch/src/Torch/Static/Factories.hs
- hasktorch/src/Torch/Static/Native.hs
- hasktorch/test/doctests.hs
> Transformer Language Model! Part Deux

- examples/static-mnist/Main.hs
- examples/static-transformer/Main.hs
- examples/static-xor-mlp/Main.hs
- hasktorch/hasktorch.cabal
- hasktorch/src/Torch/Static/NN.hs
* Remove duplicated static typed parameter.
> Merge static typed Parameter

- README.md
- examples/README.md
- examples/minimal-text-example/README.md
- examples/rnn/README.md
- examples/static-mnist/README.md
- examples/xor-mlp/Main.hs
- examples/xor-mlp/README.md
- Make dynamic xor converge consistently
- Add "Getting Started" Section to top-level readme
- Placeholder READMEs for additional examples
- Fix a few typos
> Docs + Examples Cleanup

- examples/examples.cabal
- examples/static-mnist-cnn/Main.hs
- examples/static-mnist-mlp/Main.hs
- examples/static-mnist/Common.hs
- examples/static-mnist/Monitoring.hs
This pr shows  a graph of loss-function.
I think I should use new module to show it.
> Add hvega for static-mnist-mlp

- examples/examples.cabal
- examples/image-processing/Main.hs
- hasktorch/src/Torch/Functions.hs
- hasktorch/test/FunctionsSpec.hs
- Read/Write both bitmap and png by JuicyPixels
- Add sharpness-filter
- Add lowpass-filter
> Add image-processing

- libtorch-ffi/libtorch-ffi.cabal
- libtorch-ffi/src/ATen/Managed/Native.hs
- libtorch-ffi/src/ATen/Managed/Type/Generator.hs
- libtorch-ffi/src/ATen/Managed/Type/Tensor.hs
- libtorch-ffi/src/ATen/Unmanaged/Type/Generator.hs
- libtorch-ffi/src/Torch/Managed/Native.hs
- libtorch-ffi/test/GeneratorSpec.hs
- spec/cppclass/generator.yaml
This pr supports own generator of randum number on low level api.
> Add some functions for random-generator

- hasktorch/hasktorch.cabal
- hasktorch/src/Torch/Serialize.hs
- hasktorch/test/SerializeSpec.hs
- libtorch-ffi/libtorch-ffi.cabal
- libtorch-ffi/src/Torch/Managed/Serialize.hs
- libtorch-ffi/src/Torch/Unmanaged/Serialize.hs
This pr supports serialize-function using checkpoint-file of pytorch.
> Add serialize-function for tensor

- hasktorch/src/Torch/Typed/Native.hs
- hasktorch/test/Torch/Typed/NativeSpec.hs
addressed https://github.com/hasktorch/hasktorch/issues/233 partially
> add `svd` and `choleskySolve`

- hasktorch/src/Torch/Typed/Native.hs
- hasktorch/test/Torch/Typed/NativeSpec.hs
@junjihashimoto discovered some issues and additional constraints while testing on cuda. this is the fix.
> fix svd and inverse on cuda

- deps/get-deps.sh
- nix/shared.nix
We have to upgrade libtorch having critical bug.
https://twitter.com/PyTorch/status/1192505881163902977?s=20
> Upgrade libtorch to 1.3.1

- hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs
> LSTM Fix: flatten order needs to be the same as replace order

- hasktorch/src/Torch/Typed/Tensor.hs
- hasktorch/test/Torch/Typed/TensorSpec.hs
- hasktorch/test/doctests.hs
> add spec for reshape

- .github/workflows/nix-linux.yml
- .github/workflows/nix-macos.yml
CI is broken on nix.
To fix it, upgrade cachix/install-nix-action of github-action.
https://github.com/cachix/install-nix-action/issues/10
> Upgrade cachix/install-nix-action to fix CI

- hasktorch/src/Torch/Typed/Native.hs
- hasktorch/test/Torch/Typed/NativeSpec.hs
closes #246 
@digantamisra98 added as requested.
> add mish and softplus

- .github/workflows/nix-linux.yml
- .github/workflows/nix-macos.yml
- codegen/src/RenderCommon.hs
- codegen/src/RenderTuples.hs
- deps/get-deps.sh
- libtorch-ffi/src/ATen/Managed/Native.hs
- libtorch-ffi/src/ATen/Managed/Type/StdArray.hs
- libtorch-ffi/src/ATen/Managed/Type/Tensor.hs
- libtorch-ffi/src/ATen/Managed/Type/Tuple.hs
- libtorch-ffi/src/ATen/Type.hs
- libtorch-ffi/src/ATen/Unmanaged/Native.hs
- libtorch-ffi/src/ATen/Unmanaged/Type/StdArray.hs
- libtorch-ffi/src/ATen/Unmanaged/Type/Tensor.hs
- libtorch-ffi/src/ATen/Unmanaged/Type/Tuple.hs
- libtorch-ffi/test/BasicSpec.hs
- nix/shared.nix
1, Fix quickcheck-error. See https://github.com/fpco/inline-c/pull/97 and https://github.com/fpco/inline-c/pull/99
2, Improve supporting c++template not to define each instance like `vector<tensor>` and `vector<int>`. See ATen/Type.hs.
3, Fix some CI-errors.
> Upgrade inline-c

- examples/matrix-factorization/SparseRatingMatrix.hs
- examples/minimal-text-example/Hello.hs
- examples/regression/Main.hs
- examples/rnn/Main.hs
- examples/serialization/Main.hs
- examples/vae/Main.hs
- examples/xor-mlp/Main.hs
- hasktorch/src/Torch/Functional.hs
> Add function documentation, clean up function conventions for consistency

- hasktorch/src/Torch/Functional.hs
PR made in reference to the conversation in #285 regarding completing camelCase uniformity in the repo starting with Functional.hs
> CamelCase uniformity and parameter description in Functional.hs

- .github/workflows/stack-macos.yaml
- examples/README.md
- hasktorch/src/Torch/TensorFactories.hs
Fixing up problems from https://github.com/hasktorch/hasktorch/pull/291
Updated actions/checkout@v1 to actions/checkout@v2 
with respect to https://github.com/actions/checkout/issues/23
>  Documentation, README  and actions/checkout FIX

- hasktorch/src/Torch/Typed/Functional.hs
- hasktorch/test/Torch/Typed/FunctionalSpec.hs
This PR implements the refined type of LeakyReLU.
> Add typed leakyReLU

- README.md
- experimental/jupyterlab/README.md
- experimental/jupyterlab/autogradWithSin.ipynb
Add using cachix on REAME and a example of jupyter.
> Add using cachix, and add a example of jupyter

- hasktorch/src/Torch/Typed/Aux.hs
- hasktorch/src/Torch/Typed/Functional.hs
- hasktorch/test/Torch/Typed/FunctionalSpec.hs
based on #297 for the `If` type family, this adds 2d, typed, upsampling functions.
> Upsample typed

- hasktorch/src/Torch/Utils/Image.hs
This PR adds:
* _feature in Util.Image:_ the `createTensor` function that builds an untyped Tensor from a JuicyPixels `DynamicImage` type is exposed as `fromDynImage`. Use case: preprocess images with JuicyPixels before moving the data into a Torch tensor.
> Expose function that builds a tensor from a JuicyPixel DynamicImage

- examples/load-torchscript/Main.hs
torchvision's model expects pixel's brightness between 0 to 1.
> Fix pixel's brightness between 0 to 1

- hasktorch/src/Torch/TensorFactories.hs
- hasktorch/test/FactorySpec.hs
edit: I think the nix build error appears random/unrelated...
> add untyped zerosLike like onesLike

- hasktorch/src/Torch/Functional.hs
- hasktorch/src/Torch/Typed/Functional.hs
- hasktorch/test/FunctionalSpec.hs
> add tests for untyped expand / flattenAll

- examples/README.md
- examples/autograd/Main.hs
- examples/autograd/README.md
- examples/examples.cabal
The derivation markdown can be correctly viewed [here](https://github.com/championballer/hasktorch/blob/Autograd/examples/autograd/README.md).
> Added Autograd example

- examples/mnist-mlp/Main.hs
- hasktorch/src/Torch/Serialize.hs
I found these functions useful for saving and loading weights. Are they any good or just redundant?
> add functions for saving and loading parameters for untyped models

- hasktorch/src/Torch/Functional.hs
- hasktorch/src/Torch/Typed/Functional.hs
- hasktorch/test/FunctionalSpec.hs
- hasktorch/test/Torch/Typed/FunctionalSpec.hs
Need ELU activation for reinforcement learning experimentation. Have personal experience with good performance improvement in DQN.
> Added Elu activation support for untyped tensors

- hasktorch/src/Torch/Typed/Tensor.hs
> add toBool

- hasktorch/src/Torch/Functional.hs
- hasktorch/test/FunctionalSpec.hs
This pull request is to judge reaction towards the pursuit of parity between typed and untyped functional api. If this has favourable reaction, then I will identify and add other functions which are available in typed api but not in untyped api as is identified as a goal in milestone 5 and has been also been identified in #328 in the future.
#322
> Parity between typed and untyped functional API

- examples/alexNet/Main.hs
- examples/alexNet/README.md
- examples/examples.cabal
- hasktorch/src/Torch/Functional.hs
- hasktorch/src/Torch/Functional/Internal.hs
- hasktorch/src/Torch/NN.hs
This PR implements pretrained Alexnet and all other necessary functions needed to implement it.
> Add pretrained AlexNet

- .github/workflows/cabal-linux.yml
- .github/workflows/nix-linux-cu10.yml
- .github/workflows/nix-linux-cu9.yml
- .github/workflows/nix-linux.yml
- .github/workflows/stack-macos.yaml
- codegen/codegen.cabal
- codegen/src/ParseClass.hs
- codegen/src/ParseDeclarations.hs
- examples/.hie-wrapper.sh
- examples/examples.cabal
- hasktorch/.hie-wrapper.sh
- hasktorch/hasktorch.cabal
- hasktorch/src/Torch/Typed/Functional.hs
- hasktorch/src/Torch/Typed/NN/Recurrent/GRU.hs
- hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs
- hasktorch/test/Torch/Typed/AutogradSpec.hs
- libtorch-ffi/libtorch-ffi.cabal
- libtorch-ffi/test/BasicSpec.hs
- nix/haskellExtensions/ghc-typelits-knownnat.nix
- nix/haskellExtensions/ghc-typelits-natnormalise.nix
- nix/nixpkgs.json
- nix/shared.nix
- setup-cabal.sh
- stack.yaml
lts 15 of stackage is released.
This pr fixes https://github.com/hasktorch/hasktorch/issues/276.
I think stack's build works.
But nix's build requires gcc-9 which does not work with libtorch-1.4.
cabal works without nix.
https://github.com/hasktorch/hasktorch/pull/282/checks?check_run_id=450296535
> Support for LTS15 of stackage and ghc88

- hasktorch/src/Torch/Typed/Functional.hs
I guess some modifications might be in order. 
#233
> Added some typed functions

- .github/workflows/nix-haddock-linux.yml
based on the current documentation at https://github.com/peaceiris/actions-gh-pages
> update peaceiris/actions-gh-pages to v3

- .github/workflows/cabal-linux.yml
- .github/workflows/nix-haddock-linux.yml
- .github/workflows/nix-jupyterlab.yml
- .github/workflows/nix-linux-cu10.yml
- .github/workflows/nix-linux-cu9.yml
- .github/workflows/nix-linux.yml
- .github/workflows/stack-linux.yml
See https://github.com/hasktorch/hasktorch/issues/360 .
> Free disk space on github-actions

- hasktorch/src/Torch/NN.hs
This PR modifies the initialization of untyped linear and convolution layers to match those of PyTorch.
References:
[Linear layer](https://github.com/pytorch/pytorch/blob/b64fc3c4b5d927928770f9b343eb845123367084/torch/nn/modules/linear.py#L79-L84)
[Convolution layer](https://github.com/pytorch/pytorch/blob/b64fc3c4b5d927928770f9b343eb845123367084/torch/nn/modules/conv.py#L57-L62)
> Modify initialization for untyped layers

- README.md
Remove "should only be used by contributing developers" phrase from the readme.
> Update readme comment about library usage

- .github/workflows/nix-haddock-linux.yml
- .github/workflows/nix-jupyterlab.yml
- .github/workflows/nix-linux-cu10.yml
- .github/workflows/nix-linux-cu9.yml
- .github/workflows/nix-linux.yml
- .github/workflows/nix-macos.yml
- .github/workflows/stack-nix-linux.yml
Some PRs fails during nix-installation.
So dump cachix-actions.
> Bump cachix on CI

- .github/workflows/nix-linux-cu10.yml
- .github/workflows/nix-linux-cu9.yml
- .github/workflows/nix-linux.yml
Reverts hasktorch/hasktorch#400
```
The workflow is not valid. .github/workflows/nix-linux.yml: Anchors are not currently supported. Remove the anchor 'free_disk'
```
> Revert "dedupe by yml anchors, what about across files tho?"

- README.md
- shell.nix
the haskell language server plugin can use either to format hs code
> add ormolu and brittany to the shell tools

- hasktorch/src/Torch/Typed/DType.hs
little additions that will be useful elsewhere
> add GetDType and ReplaceDType type families

- nix/default.nix
- nix/haskell.nix
- nix/sources.json
- shell.nix
- bump haskell.nix, hackage, stackage
- ghc 8.8.4
- remove ghcide from shell
- add haskell-language-server to shell
> Bump haskell nix

- hasktorch/src/Torch/Typed/Autograd.hs
- hasktorch/src/Torch/Typed/Aux.hs
- hasktorch/src/Torch/Typed/DType.hs
- hasktorch/src/Torch/Typed/Device.hs
- hasktorch/src/Torch/Typed/Factories.hs
- hasktorch/src/Torch/Typed/Functional.hs
- hasktorch/src/Torch/Typed/NN.hs
- hasktorch/src/Torch/Typed/NN/Convolution.hs
- hasktorch/src/Torch/Typed/NN/DataParallel.hs
- hasktorch/src/Torch/Typed/NN/Dropout.hs
- hasktorch/src/Torch/Typed/NN/Linear.hs
- hasktorch/src/Torch/Typed/NN/Normalization.hs
- hasktorch/src/Torch/Typed/NN/Recurrent.hs
- hasktorch/src/Torch/Typed/NN/Recurrent/Aux.hs
- hasktorch/src/Torch/Typed/NN/Recurrent/Cell/GRU.hs
- hasktorch/src/Torch/Typed/NN/Recurrent/Cell/LSTM.hs
- hasktorch/src/Torch/Typed/NN/Recurrent/GRU.hs
- hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs
- hasktorch/src/Torch/Typed/NN/Sparse.hs
- hasktorch/src/Torch/Typed/NN/Transformer.hs
- hasktorch/src/Torch/Typed/Optim.hs
- hasktorch/src/Torch/Typed/Parameter.hs
- hasktorch/src/Torch/Typed/Serialize.hs
- hasktorch/src/Torch/Typed/Tensor.hs
- hasktorch/src/Torch/Typed/Vision.hs
Seems slightly different in places nice in others, see what people think :)
> Trial adding ormolu

- .github/workflows/nix-jupyterlab.yml
- stack.yaml
This PR fixes compilation error with stack using nix.
> Change a compiler of stack to ghc-8.8.4

- README.md
- examples/static-mnist-cnn/README.md
- examples/static-mnist-mlp/README.md
Improve Nix getting started documentation to include build and running unit and a mnist example
> Improve getting started doc

- README.md
Documents how to run Hasktorch under Windows Subsystem for Linux 2 and a few troubleshooting tips
> Windows documentation

- hasktorch/src/Torch.hs
- hasktorch/src/Torch/Autograd.hs
- hasktorch/src/Torch/Backend.hs
- hasktorch/src/Torch/Cast.hs
- hasktorch/src/Torch/DType.hs
- hasktorch/src/Torch/Data.hs
- hasktorch/src/Torch/Device.hs
- hasktorch/src/Torch/Dimname.hs
- hasktorch/src/Torch/Functional.hs
- hasktorch/src/Torch/HList.hs
- hasktorch/src/Torch/Initializers.hs
- hasktorch/src/Torch/Layout.hs
- hasktorch/src/Torch/NN.hs
- hasktorch/src/Torch/Optim.hs
- hasktorch/src/Torch/Random.hs
- hasktorch/src/Torch/Scalar.hs
- hasktorch/src/Torch/Script.hs
- hasktorch/src/Torch/Serialize.hs
- hasktorch/src/Torch/Tensor.hs
- hasktorch/src/Torch/TensorFactories.hs
- hasktorch/src/Torch/TensorOptions.hs
- hasktorch/src/Torch/Typed.hs
- hasktorch/src/Torch/Vision.hs
- libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Module.hs
Hi! 👋  
Hope this works cause with stack I was not able to run locally the project 🙈  (@tscholak)
Happy Hacktoberfest! 🚀 
---
UPDATE: made it work locally with Nix ❄️ , thanks @tscholak! 🙌
> Apply hlint + ormolu 💅🏼

- hasktorch/src/Torch/NN.hs
- hasktorch/src/Torch/Scalar.hs
- libtorch-ffi/src/Torch/Internal/Managed/Type/Scalar.hs
- libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Scalar.hs
This PR is part of these PRs, because some test/compilation failed with typed api.
https://github.com/hasktorch/hasktorch/pull/346
https://github.com/hasktorch/hasktorch/pull/348
> Add parameterized scalar for untyped api

- hasktorch/src/Torch/Tensor.hs
- hasktorch/src/Torch/TensorFactories.hs
- hasktorch/src/Torch/Typed/Functional.hs
- hasktorch/src/Torch/Typed/NN/Recurrent/GRU.hs
- hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs
- hasktorch/test/FactorySpec.hs
- Add arange of TensorFactory.
- Add TensorLike instance of Tensor
- Add some dtype-options
- Improve show instance of multi dimensional tensor.
> Add arange

- experimental/bounding-box/Main.hs
- experimental/bounding-box/README.md
- experimental/experimental.cabal
- hasktorch/src/Torch/Vision.hs
This PR provides lightweight methods of drawing bounding doxes.
This function is needed to evaluate object detection.
> Add drawString and drawLine to draw bounding boxes

- examples/mnist-mlp/Main.hs
- hasktorch/src/Torch/NN.hs
- hasktorch/src/Torch/Tensor.hs
- hasktorch/test/NNSpec.hs
- hasktorch/test/Torch/Typed/VisionSpec.hs
This pr fixes https://github.com/hasktorch/hasktorch/issues/501.
Fixed mnist-mlp to support CUDA.
> Improve mnist-mlp to support for CUDA

- hasktorch/src/Torch/Tensor.hs
- hasktorch/test/TensorSpec.hs
See https://github.com/hasktorch/hasktorch/issues/520 .
> Fix empty tensors

- hasktorch/src/Torch/Tensor.hs
asTensor' with CUDA causes a segmentation fault, because it allocates memory on cuda, and writes to it from cpu.
We can reproduce it with the following code.
```
let dev = (Device CUDA 0)
let u = asTensor' ([1,2,3]::[Float]) $ withDevice dev defaultOpts
show u
```
This PR fixes the bug.
> Fix asTensor'

- .github/workflows/nix-linux.yml
- nix/sources.json
Running update of the niv dependencies, which should trigger new cachix.
Things still compiling on my end but will report back once done.
> Update niv dependencies

- nix/haddock-combine.nix
This PR fixes quickdump of https://hasktorch.github.io.
https://github.com/hasktorch/hasktorch/issues/529
Merge doc-index.json files of cabal-packages just as cardano-node does.
https://github.com/input-output-hk/cardano-node/blob/master/scripts/haddocs.sh#L97-L108
> Fix quickjump

- .github/workflows/cabal-linux.yml
- .github/workflows/stack-linux.yml
- .github/workflows/stack-macos.yaml
- .github/workflows/stack-nix-linux.yml
Use cache to reduce stack CI time.
> Add the cache of .stack

- hasktorch/doc/06-linear-regression.md
Miscellaneous fixes for tutorial.
> Tutorial fixes

- nix/haskell.nix
https://github.com/input-output-hk/haskell.nix/issues/1197
> Remove set-git-rev to improve the usage of cache

- hasktorch/src/Torch/Typed/Tensor.hs
- hasktorch/test/Torch/Typed/TensorSpec1.hs
It provides some examples to convert from untyped to typed.
> Add some examples using withTensor to convert untyped tensor to typed one

- hasktorch/hasktorch.cabal
- hasktorch/src/Torch/Typed/Auxiliary.hs
- hasktorch/src/Torch/Typed/Tensor.hs
- hasktorch/src/Torch/Typed/VLTensor.hs
- setup-cabal.sh
Adds a VLTensor that represents a tensor whose length is determined at runtime with existential quantification
> Add a variable length tensor for typed api

- hasktorch/hasktorch.cabal
- hasktorch/src/Torch/Jit.hs
This PR speeds up a function having many FFI calls by converting them to torchscript.
> Add a function of memoization for torchscript

- examples/model-serving/02-train-inference/Model.hs
- examples/model-serving/03-serialization/Model.hs
The example code had ambiguous record fields used which made it impossible to compile the project.
> Fix Compilation Errors

- cabal.project
- codegen/codegen.cabal
- libtorch-ffi/libtorch-ffi.cabal
- setup-cabal.sh
- stack.yaml
Fix this issue https://github.com/hasktorch/hasktorch/issues/678 .
> Bump inline-c to 0.9.1.10

- libtorch-ffi/csrc/hasktorch_finializer.cpp
- libtorch-ffi/csrc/hasktorch_profile.h
- libtorch-ffi/src/Torch/Internal/Unmanaged/Optim.hs
- libtorch-ffi/src/Torch/Internal/Unmanaged/Serialize.hs
- libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Module.hs
See https://github.com/hasktorch/hasktorch/issues/706
This PR redefines PROFILING to avoid conflicts.
> Add hasktorch_profile.h to avoid conflicts of the PROFILING definition

- .github/workflows/stack-linux.yml
- hasktorch/hasktorch.cabal
- hasktorch/src/Torch/Backend.hs
- hasktorch/src/Torch/Device.hs
- hasktorch/src/Torch/Random.hs
- hasktorch/src/Torch/Tensor.hs
- hasktorch/src/Torch/TensorOptions.hs
- hasktorch/src/Torch/Typed/Auxiliary.hs
- hasktorch/src/Torch/Typed/Factories.hs
- hasktorch/src/Torch/Typed/Functional.hs
- hasktorch/src/Torch/Typed/Tensor.hs
- libtorch-ffi/libtorch-ffi.cabal
- libtorch-ffi/src/Torch/Internal/Const.hs
- libtorch-ffi/src/Torch/Internal/GC.hs
- libtorch-ffi/src/Torch/Internal/Managed/Type/Context.hs
- libtorch-ffi/src/Torch/Internal/Managed/Type/Generator.hs
- libtorch-ffi/src/Torch/Internal/Managed/Type/Tensor/Tensor0.hs
- libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Context.hs
- libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Generator.hs
- libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Tensor/Tensor0.hs
- libtorch-ffi/test/MpsSpec.hs
- libtorch-ffi/test/Spec.hs
* Add MPS for device-type and backend
* MPS does not support double-type.
> GPU Support for macOS

- hasktorch/hasktorch.cabal
- hasktorch/src/Torch/Typed/Serialize.hs
- hasktorch/test/Spec.hs
- hasktorch/test/Torch/Typed/SerializeSpec.hs
> Add loadParameters and saveParameters

- hasktorch/src/Torch/Typed/Tensor.hs
Wrote this while using hasktorch for a project, and figured I should send a PR to add it.
Hopefully the code style is acceptable; I tried to make the indentation and line spacing match with the other functions in the file, although it didn't feel right to remove the kind signatures so I left those as I'd originally written them in my project.
I'm open to writing tests if needed.
Decided to put it in `Typed.Tensor` rather than `Typed.Functional` because the untyped `indexSelect` is in `Torch.Tensor`, but I could see it in either place.
There's a potential shape-safety issue in that the `Int64`s in `index` could be larger than the relevant dimension of `input`; as far as I'm aware, there isn't really any way to implement `indexSelect` that doesn't have this problem, but maybe there should …
> Typed form of indexSelect

- libtorch-ffi/Setup.hs
When macos, the link error happens as follows:
```
duplicate symbol 'vtable for c10::intrusive_ptr_target' in:
/Users/junji.hashimoto/git/hasktorch-libtorch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/libtorch-ffi-2.0.1.5/build/Torch/Internal/Unmanaged/Type/C10Dict.dyn_o
/Users/junji.hashimoto/git/hasktorch-libtorch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/libtorch-ffi-2.0.1.5/build/Torch/Internal/Unmanaged/Type/C10List.dyn_o
duplicate symbol 'vtable for c10::VariableVersion::VersionCounter' in:
/Users/junji.hashimoto/git/hasktorch-libtorch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/libtorch-ffi-2.0.1.5/build/Torch/Internal/Unmanaged/Type/Extra.dyn_o
/Users/junji.hashimoto/git/hasktorch-libtorch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/libtorch-ffi-2.0.1.5/build/Torch/Internal/Unmanaged/Aut …
```
> Add -optl-ld_classic for macos and -rpath

- setup-cabal.sh
Also update script with shellcheck hints.
> chore: Remove dead references to deps folder in cabal setup script.
