vendor/build-error-handler.sh
Match the compiler requirement in `build-aten.sh` and `build-error-handler.sh` when building on Mac.
=> Changed the requirement of gcc-6 to gcc-7 when building on Mac

core/hasktorch-core.cabal, core/package.yaml, core/src/Torch/Raw/Internal.hs, core/src/Torch/Raw/Storage.hs, core/src/Torch/Raw/Tensor/Generic.hs, core/src/generic/Torch/Core/Tensor/Dynamic/Double.hs, stack.yaml
`printTensor` on 1d and 2d double tensors now print properly formatted values.
Closes #53.
=> Introduced dispRawRealFloat for pretty printing 1d and 2d DoubleTensor.

codegen/README.md
Fixed a dead link to TH in the codegen/Readme.md so it now points to the TH library within the PyTorch project.
=> Update TH Reference in codegen/Readme.md

DEVELOPERS.md, cabal.project.freeze
I put the solution for the Aten library linking issue in DEVELOPERS.md. 
It would perhaps be useful to put this command somewhere in the build script itself? I'm mildly scared of making a change to the build script and somehow breaking the build system even further, however, so I wrote it down as a "here's the duct tape to fix this issue" thing.
=> Put solution to aten library linkage issue

build.nix, shell.nix
Some quirks which came up:
- our backend, `libATen-0.4.0`, doesn't seem to build with cuda-10 or cuda-9.2
- cudatoolkit_9_0 can't build with the default gcc (the version must be less than 6).
- magma-2.3.0, which is magma's hosted documentation, can't build with gcc5 -- I've bumped it up to magma-2.4.0.
While [cuda 9.0 is supposedly compatible with nvidia 410](https://devtalk.nvidia.com/default/topic/1042638/is-nvidia-driver-410-57-incompatible-with-cuda-9-0/?offset=5), I get a runtime error when building hasktorch-thc:
```
THCudaCheck FAIL file=/tmp/nix-build-hasktorch-aten.drv-0/aten/src/THC/THCGeneral.cpp line=70 error=35 : CUDA driver version is insufficient for CUDA runtime version
terminate called after throwing an instance of 'std::runtime_error'
what():  cuda runtime error (35) : …
```
=> Build nix-shell for gpu support

stack.yaml
This PR is trial to use stack. 
But following error happens.
```
> stack build
...
Building all executables for `hasktorch-signatures' once. After a successful build of all of them, only specified executables will be rebuilt.
hasktorch-signatures        > configure (lib + internal-lib + exe)
hasktorch-signatures        > Configuring hasktorch-signatures-0.0.1.0...
hasktorch-signatures        > Error:
hasktorch-signatures        >     The following packages are broken because other packages they depend on are missing. These broken packages must be rebuilt before they can be used.
hasktorch-signatures        > planned package hasktorch-signatures-0.0.1.0 is broken due to missing package hasktorch-signatures-partial-0.0.1.0-FkbKtqZSXzwLiEkfE3RTVZ+4wgymxdvbu48ub
hasktorch-signatures        > …
```
=> Add stack.yaml

codegen/codegen.cabal, examples/examples.cabal, ffi/libtorch-ffi.cabal, hasktorch/hasktorch.cabal
Before uploading this package to hackage, this pr renames `ffi`-package to `libtorch-ffi`-package.
=> Rename the package-name from ffi to libtorch-ffi

deps/get-deps.sh, libtorch-ffi/libtorch-ffi.cabal
libtorch begins to provide binaries using C++11ABI.
(Old C++ABI with  -D_GLIBCXX_USE_CXX11_ABI=0 is to keep backward compatibility for nvcc using gcc-4.)
https://discuss.pytorch.org/t/issues-linking-with-libtorch-c-11-abi/29510/2
https://github.com/hasktorch/hasktorch/pull/162
This PR changes the C++ABI to C++11ABI.
=> Drop -D_GLIBCXX_USE_CXX11_ABI=0

hasktorch/src/Torch/Static/Native.hs
see https://pytorch.org/docs/stable/nn.functional.html?highlight=nll_loss#torch.nn.functional.nll_loss for the version in pytorch and https://pytorch.org/docs/stable/_modules/torch/nn/functional.html#nll_loss for the implementation.
there's no check so far on `target` or on `ignoreIndex`.
each element value in `target` has to fulfill `0 <= value < c`, where `c > 0` is the number of classes.
the purpose of `ignoreIndex` and it's constraints are poorly understood by me at this point.
=> add nll_loss implementation

hasktorch/src/Torch/Tensor.hs, hasktorch/test/TensorSpec.hs
The size of Bool-type is different between Haskell and C++.
Haskell's bool is 4bytes.
```
> :m + Foreign.Storable
> sizeOf (True :: Bool)
4
```
C++'s bool is 1byte.
```
$ cat test.cpp
#include <iostream>
using namespace std;
int
main (){
cout << sizeof(bool)  << endl;
return 0;
}
$ g++ test.cpp ; ./a.out
```
Tensorlike-class uses the data-size of Haskell to store the value in libtorch's memory.
This PR fixes the mismatch.
=> Fix the mismatch of Bool-type between C++ and Haskell

examples/static_xor_mlp/Main.hs, hasktorch/hasktorch.cabal, hasktorch/src/Torch/DType.hs, hasktorch/src/Torch/Functions.hs, hasktorch/src/Torch/Static.hs, hasktorch/src/Torch/Static/Native.hs, hasktorch/src/Torch/Tensor.hs, hasktorch/test/StaticSpec.hs, hasktorch/test/doctests.hs, nix/ghc-typelits-knownnat.nix
~this is becoming a bit of a larger experiment.~ **This is ready for review now!**
I needed to do some type-level programming with `DType`s for `logsumexp` and others.
This required the following change for statically typed tensors:
```
data Tensor (dtype :: DType.DType) (shape :: [Nat]) where
UnsafeMkTensor :: forall dtype shape . { toDynamic :: D.Tensor } -> Tensor dtype shape
```
(here in GADT syntax).
However, this remains very much an experiment. This so far does not support reification of Haskell types as it has been accomplished with the `Reifies` type class.
~I also pushed version 0.7 of `ghc-typelits-knownnat` for the `KnownBool` typeclass.~ (this can wait)
~there is an unresolved issue: the return values for `all`, `any`, `all'`, `any'` are wrong, and this has nothing to do with …
=> type-level programming with DType

.circleci/config.yml, .github/workflows/cabal-linux.yml, .github/workflows/nix-linux.yml, .github/workflows/nix-macos.yml, .github/workflows/stack-linux.yml
Sometimes, CI fails for not enough memory.
Circleci's instance has 4GB. Github-actions's one has [7GB](https://github.com/features/actions
).
So this PR changes CI-instances into github-actions's one.
I remain "osx-stack-build" on circleci, because the build is stable.(I do not know why it is stable.)
and  CircleCi is usable to debug. It can allow ssh-login.
=> Move some CI-builds to github-actions

examples/static-mnist-cnn/Main.hs, examples/static-mnist-mlp/Main.hs, examples/static-mnist/Image.hs, examples/static-transformer/Main.hs, examples/static-xor-mlp/Main.hs, examples/test/ImageSpec.hs, hasktorch/hasktorch.cabal, hasktorch/src/Torch/Typed.hs, hasktorch/src/Torch/Typed/Factories.hs, hasktorch/src/Torch/Typed/NN.hs, hasktorch/src/Torch/Typed/Native.hs, hasktorch/test/TypedSpec.hs, hasktorch/test/doctests.hs
When people hear static on deep learning context, they think of static graph.
hasktorch does not create static graph. 
static of hastorch means statically typed data.
This pr renames static to typed, because it is confusing.
=> Rename Static to Typed

examples/static-mnist-cnn/Main.hs, examples/static-mnist-mlp/Main.hs, examples/static-mnist/Common.hs, hasktorch/hasktorch.cabal, hasktorch/src/Data/HList.hs, hasktorch/src/Torch/Typed/Autograd.hs, hasktorch/src/Torch/Typed/Aux.hs, hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs, hasktorch/src/Torch/Typed/Native.hs, hasktorch/src/Torch/Typed/Optim.hs, hasktorch/src/Torch/Typed/Parameter.hs, hasktorch/src/Torch/Typed/Serialize.hs
I added typed optimizers to the core hasktorch lib and used them for the typed mnist mlp example. Please have a look in `Torch.Typed.Autograd` and `Torch.Typed.Optim`. I still want to implement a test suite based on the test functions @austinvhuang used for the `Optimizers` example module and following some of the tests in pytorch, cf. https://github.com/pytorch/pytorch/blob/master/test/test_optim.py.
The mlp code compiles fine and runs without error, but learning isn't working yet:
```
[nix-shell:~/Projects/thirdParty/hasktorch/examples/static-mnist]$ DEVICE="cpu" ../dist/build/static-mnist-mlp/static-mnist-mlp
Iteration: 250. Training batch loss: 2.7391508. Test loss: 1.8653502. Test error-rate: 0.56799316
Iteration: 500. Training batch loss: 3.7517178. Test loss: 2.6845038. Test …
```
=> typed gradients and optimizers

.github/workflows/nix-haddock-linux.yml, default.nix, nix/haddock-combine.nix, nix/shared.nix
This pr builds haddock by using nix, then it deploys the docs to hasktorch.github.io repo. 
The nix script generating haddock is the same as plutus's one (https://github.com/input-output-hk/plutus/blob/master/nix/haddock-combine.nix).
=> Add CI-integration of haddock

README.md, examples/shell.nix, hasktorch/shell.nix, nix/shared.nix, setup-cabal.sh, stack.yaml
This PR adds a nix-shell development workflow to the README and logs some suggestions for getting `stack` and `cabal v2-*` to work in a nix shell (since neither workflow uses the NixOS packagesets).
In particular, it logs [setup-cabal.sh#L5-L6](https://github.com/hasktorch/hasktorch/blob/master/setup-cabal.sh#L5-L6) in [the shellHook](https://github.com/hasktorch/hasktorch/pull/259/files#diff-c156cac2b10c7abb0ec25d4ec2622875R197-R199) which explains to a nix user how to create a freeze file. This freeze file gets the correct version of inline-c-cpp via sed and avoids cabal-hell with `show-prettyprint` (see https://github.com/hasktorch/hasktorch/pull/259#discussion_r357858259)
=> add cabal v1/v2 + stack workflows to shared.nix shellHook

nix/shared.nix
With this PR, the nix overlay can be imported and combined with other overlays.
E.g. to setup jupyterWith with hasktorch you can then do:
```
hasktorchOverlay = (import ./hasktorch/nix/shared.nix { compiler = "ghc865"; }).overlayShared;
haskellOverlay = import ./haskell-overlay.nix;
pkgs = import nixpkgsPath {overlays = [ hasktorchOverlay haskellOverlay ]; config={allowUnfree=true;};};
```
`haskellOverlay` is a custom overlay that adds other packages on top of the hasktorch changes.
=> make nix overlay accessible

examples/static-mnist/Common.hs, hasktorch/hasktorch.cabal, hasktorch/src/Torch/Typed/Autograd.hs, hasktorch/src/Torch/Typed/DType.hs, hasktorch/src/Torch/Typed/Device.hs, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/src/Torch/Typed/NN.hs, hasktorch/src/Torch/Typed/Parameter.hs, hasktorch/src/Torch/Typed/Tensor.hs, hasktorch/test/Torch/Typed/AutogradSpec.hs, hasktorch/test/Torch/Typed/FunctionalSpec.hs, hasktorch/test/Torch/Typed/OptimSpec.hs, hasktorch/test/Torch/Typed/TensorSpec.hs
~this is wip~
This is ready for review!
I implemented two mechanisms:
One for moving (parts of) model ADTs from one device to different one and another mechanism for changing the data type of (parts of) a model ADT.
These mechanisms have very similar implementations and generalize `toDevice` and `toDType`, respectively.
They work kind of like a lens, and they need a `Generic` instance for the model data type. Furthermore, the model data type must be parameterized over at least one device type or at least one dtype type, respectively. I used type families to walk the type parameters of the model data type until I find the device or dtype I want to change.
This idea came to me after reading the generic-lens paper by Csongor Kiss et al.
=> add HasToDevice class and instances

hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs
functionally, nothing has changed, but instead of these ad-hoc `HasSampleStuff` classes and instances, we use `A.Randomizable`.
Here's how you work with this:
```haskell
:set prompt "λ> "
:seti -XTypeApplications
:seti -XDataKinds
:seti -XScopedTypeVariables
import Torch.HList
import Torch.Typed.NN.Recurrent.LSTM
import Torch.Typed.Tensor
import Torch.Typed.Parameter
import Torch.Typed.NN
import Torch.Typed.Functional
import Torch.Typed.Factories
import qualified Torch.DType as D
import qualified Torch.Device as D
import qualified Torch.NN as A
spec = LSTMSpec @5 @7 @3 @'Bidirectional @'D.Float @'( 'D.CPU, 0) (DropoutSpec 0.1)
model <- A.sample spec
:t flattenParameters model
spec' = LSTMWithConstInitSpec spec Torch.Typed.Factories.zeros Torch.Typed.Factories.zeros
model' <- A.sample …
```
=> revise LSTM random sampling classes and instances to make them agree with hasktorch idioms

examples/regression/Main.hs
This is a small PR that makes the import list explicit in the regression example. As a newcomer to hasktorch, it has been useful for me to better track functions and data types. I thought it might also be useful for other newcomers.
I followed the import style guide instruction from here:
https://github.com/tweag/guides/blob/master/style/Haskell.md
=> Making import list explicit in regression example

hasktorch/test/Torch/Typed/FunctionalSpec.hs, libtorch-ffi/src/Torch/Internal/Managed/Type/Context.hs
When using a certain seed, test fails. 
But we do not know the seed used in the test.
This pr outputs using seed before test to find out the cause of the error.
https://github.com/hasktorch/hasktorch/runs/437503475?check_suite_focus=true
=> Print current seed before test

hasktorch/src/Torch/Typed/Aux.hs, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/test/Torch/Typed/FunctionalSpec.hs
Assuming doctests don't balk at the test, this should be functional.   I needed a `FromJust` type family to work with the existing families which is maybe more principled than writing a dedicated type family at the cost of exposing unnecessary logic.
=> add topk typed implementation

hasktorch/src/Torch/Functional.hs
SELU and CELU included latex formats were not being rendered properly (as also mentioned in #290) , plus there was an extra '|' in diag, which has also been removed to maintain uniformity in the docstrings of Functional.hs
=> Modified diag, SELU and CELU docstrings 

hasktorch/src/Torch/Typed/Functional.hs, hasktorch/test/Torch/Typed/FunctionalSpec.hs
this is my wip attempt at adding typed mean ops,
pretty much just copied over from their median variants.
this is currently still yielding errors:
```haskell
> /meltan/downloads/repos/hasktorch/hasktorch/src/Torch/Typed/Functional.hs:3941:35: error:
>     • Could not deduce (ATen.CppTuple2 (ForeignPtr ATen.Tensor))
>         arising from a use of ‘ATen.cast2’
>       from the context: KnownNat d
>         bound by the type signature for:
>                    meanDim :: forall (d :: Nat) (shape :: [Nat]) (dtype :: D.DType) (device :: (D.DeviceType,
>                                                                                                 Nat)).
>                               KnownNat d =>
>                               Tensor device dtype shape
>                               -> …
```
=> Add typed mean ops (wip)

hasktorch/hasktorch.cabal, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/src/Torch/Typed/NN/Recurrent/Cell/GRU.hs, hasktorch/test/Torch/Typed/FunctionalSpec.hs, hasktorch/test/Torch/Typed/NN/Recurrent/Cell/GRUSpec.hs, hasktorch/test/Torch/Typed/NN/Recurrent/Cell/LSTMSpec.hs
This PR implements refined type of gruCell in Torch.Typed.Functional,
GRUCell in Torch.Typed.NN.Recurrent.Cell.GRU,
and adds tests for LSTMCell and GRUCell in Torch.Typed.NN.Recurrent.Cell
=> Add typed GRUCell with tests

hasktorch/src/Torch/Functional.hs
I left a commented version of `flatten` as in the typed module -- no clue what the reasoning was there.
=> add untyped expand/flattenAll

hasktorch/src/Torch/Functional.hs, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/test/Torch/Typed/FunctionalSpec.hs
names `all'` / `any'` feel sorta inconsistent with `*Dim` names used for sum/min/max/median/mean... I feel the latter are more clear.
=> rename all' / any' to allDim / anyDim

examples/gaussian-process/Main.hs, examples/load-torchscript/Main.hs, examples/matrix-factorization/SparseRatingMatrix.hs, examples/minimal-text-example/Hello.hs, examples/mnist-mlp/Main.hs, examples/optimizers/TestFunctions.hs, examples/regression/Main.hs, examples/rnn/Main.hs, examples/serialization/Main.hs, examples/static-xor-mlp/Main.hs, examples/vae/Main.hs, examples/xor-mlp/Main.hs, experimental/dataloader-cifar10/Main.hs, hasktorch/src/Torch/Functional.hs, hasktorch/src/Torch/Initializers.hs, hasktorch/src/Torch/Optim.hs, hasktorch/src/Torch/Typed/NN/Recurrent/GRU.hs, hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs, hasktorch/src/Torch/Vision.hs, hasktorch/test/FunctionalSpec.hs, hasktorch/test/OptimSpec.hs
I think there may be some controversial functions in here -- let's discuss which ones we want what way. :)
For the part-tensor-part-scalar ops at least I think we'd probably want tensor param last.
For the non-associative ones there (subtract, divide), we'd probably need versions with either side (both `a` and `b` for e.g. `a - b`) as the tensor, but in that case we may wanna try and ensure the naming of the tensor-only and both half-tensor ops to somehow align to make sense as well...
I haven't put much thought into that yet.
=> Torch.Functional param order: subject-last

codegen/src/RenderCommon.hs, codegen/src/RenderPure.hs, hasktorch/src/Torch/Functional.hs, hasktorch/src/Torch/Functional/Internal.hs, spec/bindings.yaml
This PR adjusts the codegen behavior for the `Functional.Internal` module to include overloaded functions under their masked names.
I've since gone over the extra functions generated this way, and made an attempt to rename them to something semi-intelligible.
=> codegen overloaded functions

examples/image-processing/Main.hs, examples/load-torchscript/Main.hs, hasktorch/src/Torch/Vision.hs
readImage function reads jpeg-file as YCbCr-format.
It is not convenient for some applications.
readImageAsRGB8 function always read a image as RGB8-format.
=> Add readImageAsRGB8 to read jpeg-file as RGB8-format

hasktorch/src/Torch/Autograd.hs
I wanted to add this warning based on an error I ran into:
`CppStdException "Exception: One of the differentiated Tensors does not require grad; type: std::runtime_error"`
=> warn about IndependentTensor vs makeIndependent

hasktorch/src/Torch/Typed/Functional.hs
[slack discussion](https://hasktorch.slack.com/archives/C75PY1W0J/p1586556310092600):
> `squeezeAll`  is unsafe, the type squeezes out known `1`s but leaves in unknowns, while at run-time those that then turn out 1 are also squeezed out.
5 replies
> (I'm not sure this function can be safely typed, as essentially the number of dimensions suddenly becomes unknown...)
> I'm pretty much gonna put this one on my blacklist
> a typed solution here would mean some new type for a dimension like `[a, b?, c, d]` , but doubting that's gonna happen anytime soon, might the best option for now just be to put a disclaimer in its docstring?
> alternatively, we can make this function safe by restricting its use to `KnownShape`s, demanding that all dimensions are statically known.
> oh, `KnownShape` …
=> add squeezeAll warning

hasktorch/src/Torch/Functional.hs, hasktorch/test/FunctionalSpec.hs
Extension of #337 to address #328 . Includes stack, sumDim, topK, triu, tril, unSqueeze functions along with tests in untyped api.
=> Added function definitions for untyped api to reduce parity

libtorch-ffi/libtorch-ffi.cabal, nix/shared.nix
The build of nix with cuda does not work (https://github.com/hasktorch/hasktorch/runs/611457740) , 
because torch_cuda's option is ignored on haskellPackagesOld.callCabal2nix.
callCabal2nixWithOptions can add  not ignored the flag of cabal.
=> Fix cuda's branch

hasktorch/src/Torch/Functional.hs, hasktorch/test/FunctionalSpec.hs
Would having a datatype for diagonal help? Since more functions crept up with that as a parameter in the last PR (#357 ) i.e. tril and triu in addition to the previously present diag. Thought of this change in reference to #322 .
=> Added datatype for diagonal in untyped api

deps/get-deps.sh
We so far called [`$PYTHON aten/src/ATen/gen.py`](https://github.com/hasktorch/hasktorch/blob/master/deps/get-deps.sh#L127), which depends on `pyyaml`.
If that wasn't preinstalled, the script failed.
=> get-deps: install python dependency pyyaml

hasktorch/src/Torch/Functional.hs
Exposed functionality for functions that I feel would be useful in day to day use of Hasktorch. Please tell me if any changes are in order, or you feel any other function should be exposed through this PR. 
#328 #322
=> Exposed common functions, added documentation, and modified cosine similarity

examples/distill/Dataset.hs, examples/distill/Distill.hs, examples/distill/Main.hs, examples/distill/README.md, examples/examples.cabal, hasktorch/hasktorch.cabal, hasktorch/src/Torch/Functional.hs, hasktorch/src/Torch/NN.hs, hasktorch/src/Torch/Vision.hs, hasktorch/test/ScriptSpec.hs
Description from the README:
Trains MNIST on a larger neural network (MLP 2 hidden layers of 300 dimensions each), distills to a student network (MLP 2 hidden layers of 30 dimensions each) using soft target distribution.
Trains students with soft targets per [Hinton, Vinyals, Dean 2015](https://arxiv.org/abs/1503.02531) with a temperature parameter of 20.
Distillation module operations are decoupled from details of this example. In particular a distillation process is paramaterized as a teacher model, a student model, view functions into both teacher and student (given an input) and a distillation loss that compares the views.
```
data (Parameterized t, Parameterized s) => DistillSpec t s = DistillSpec {
teacher :: t,
student :: s,
teacherView :: t -> Tensor -> ModelView,
studentView :: s …
```
=> Distillation Example

hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs, hasktorch/src/Torch/Typed/Parameter.hs
I was making a model that included both parts known statically as well as dynamic ones, meaning typed optimization was out for me.
This means I'd need to fall back to untyped optimization, while I was still using the typed LSTM here as well. As a result, I needed to ensure that supported untyped optimization (i.e. instance `A.Parameterized`). This PR adds that.
I'm open to feedback on the function `untypeParam` -- I was under the impression we didn't have something like it yet, and I wanted to use a name that wouldn't clash with `toDynamic`, wouldn't sound like a noun (`dynamicParameter`), and ideally wouldn't be super long, as this may get repeated a bunch in lists (see `LSTMLayer` instance). So I was a bit on the fence, but I'm open to e.g. `untypeParameter` or other ideas if preferred.
=> allow untyped optimization for typed LSTM

hasktorch/src/Torch/Functional.hs, hasktorch/test/FunctionalSpec.hs
- Add Eq instance to tensors as `all (eq t1 t2)
- Add loss: klDiv, CTC
- Add logical*: logicalNot, logicalXor, logicalAnd, logicalOr
- Add is*: isclose, isnan, isNonzero, isSameSize, isSigned
- Add diag*: diagEmbed, diagflat, diagonal
- Add erfc, erfinv, logsumexp
- Add *gamma: lgamma, digamma, polygamma, mvlgamma
- whitelist a few trivial ops from Internal
- Start grouping Functional ops into blocks of related concepts (may refactor as separate modules in the future to try improving compilation time)
=> Add new untyped bindings to Functional module

hasktorch/hasktorch.cabal, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/test/doctests.hs
This PR makes sure the doctests for `hasktorch` build by default.
This also fixes up a small problem with the doctests.
This PR also makes sure that the doctests are run in CI.  Currently, `master` does not appear to be actually running the doctests.
=> Enable doctests to build by default again.

.github/workflows/stack-nix-linux.yml, README.md, nix/stack-shell.nix, stack.yaml
This PR gets stack.yaml usable again for actually compiling with `stack`.
=> Get stack.yaml working again, building with nix

examples/static-xor-mlp/Main.hs, hasktorch/test/Torch/Typed/AuxSpec.hs
the static-xor-mlp example was broken. I fixed it.
=> Fix static-xor-mlp example

examples/static-xor-mlp/Main.hs, hasktorch/src/Torch/Typed/Optim.hs, hasktorch/src/Torch/Typed/Tensor.hs, hasktorch/test/Torch/Typed/AutogradSpec.hs, hasktorch/test/Torch/Typed/OptimSpec.hs
When we define cuda's number and use it, it throws following exception.
This PR is to fix the exception.
``` 
0.5 :: Tensor '( 'D.CUDA, 0) 'D.Float '[]
```
```
*** Exception: CppStdException "Exception: the derivative for 'target' is not implemented; type: std::runtime_error"
```
=> Move literal number to device's place

hasktorch/src/Torch/Typed/Functional.hs
This PR adds a typed `mode` operator, as per #233.
I just talked to @tscholak, and he suggested that I should check that this operator actually works on CUDA.  I don't have an nvidia GPU, so I haven't done this, but I would appreciate if someone could check this for me.
Also, because I added the doctests, I didn't add any hspec tests, but I could do this if necessary.
(Note that this PR is based on the current `master`, which does not yet contain a fix for actually running the doctests in CI, but I did check that the doctests I added here run correctly locally.)
=> Add a typed mode operator.

examples/distill/Distill.hs, examples/distill/Main.hs, hasktorch/src/Torch/NN.hs, hasktorch/src/Torch/Typed/NN.hs
Move HasForward into Torch.NN for untype API.
This PR is useful to allow not Tensor's type for input-argument e.g.`Parameterized a => a -> [Tensor] -> Tensor`.
=> Move HasForward to Torch.NN

.github/workflows/cabal-linux.yml, cabal.project
In CI of github-actions, we use write-ghc-environment-files=always for doctest.
When we test packages on local environment, we sometimes forget to add the option and test fails.
This pr adds write-ghc-environment-files=always to cabal.project not to forget the option.
=> Add write-ghc-environment-files=always for doctest

hasktorch/src/Torch/Functional.hs, hasktorch/src/Torch/Tensor.hs, hasktorch/test/TensorSpec.hs, libtorch-ffi/csrc/hasktorch_finializer.cpp, libtorch-ffi/csrc/hasktorch_finializer.h, libtorch-ffi/libtorch-ffi.cabal, libtorch-ffi/src/Torch/Internal/Managed/Type/TensorIndex.hs, libtorch-ffi/src/Torch/Internal/Type.hs, libtorch-ffi/src/Torch/Internal/Unmanaged/Type/TensorIndex.hs
This PR adds slice-operators.
It is made in the same way as C++ syntax.
Pytorch(Python) | Pytorch(C++)| This PR
-- | -- | -- 
None | None | None
Ellipsis | Ellipsis | Ellipsis
... | "..." | Ellipsis
123 | 123 | 123
True | true | True
False | false | False
: or :: | Slice() or Slice(None, None) or Slice(None, None, None) | ()
1: or 1:: | Slice(1, None) or Slice(1, None, None) | Slice 1
:3 or :3: | Slice(None, 3) or Slice(None, 3, None) | Slice (None,3)
::2 | Slice(None, None, 2) | Slice (None,None,2)
1:3 | Slice(1, 3) | Slice (1,3)
1::2 | Slice(1, None, 2) | Slice (1,None,2)
:3:2 | Slice(None, 3, 2) | Slice (None,3,2)
1:3:2 | Slice(1, 3, 2) | Slice (1,3,2)
torch.tensor([1, 2]) | torch::tensor({1, 2}) | asTensor([1,2])
=> Add slice-operators

hasktorch/src/Torch/Typed/Functional.hs, hasktorch/test/Torch/Typed/FunctionalSpec.hs
#233 
**EDIT**: this PR just adds `diag` to `Torch.Typed.Functional`. The comments below the line are resolved.
TODO
----
(outdated)
So far I've only attempted `diag`. I approached this by splitting into 2 branches (`upperDiag` and `lowerDiag`), which return diagonals above and below the main diagonal, respectively (this is so the index can be a natural).
I also considered implementing this as a single function with a `Bool` type parameter, i.e. something like
``` haskell
diag
:: forall (index :: Nat) (upper :: Bool) (i :: Nat) (j :: Nat) device dtype
. (KnownNat index, KnownBool upper)
=> Tensor device dtype '[i, j] -- ^ input
-> Tensor device dtype '[Min i j - index] -- ^ output
diag t = unsafePerformIO $ ATen.cast2 ATen.Managed.tensor_diag_l t index
where
absIndex = natValI @index …
```
=> Add typed diag

hasktorch/src/Torch/Functional.hs, hasktorch/test/FunctionalSpec.hs
Fixes #416.
I also went ahead and removed the `Offset` type and instance as there weren't any other uses.
=> Allow full domain of offset values in diag* functions

hasktorch/src/Torch/Typed/Aux.hs, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/test/Torch/Typed/FunctionalSpec.hs
This PR adds typed versions of [`diagEmbed`](https://pytorch.org/docs/stable/torch.html?highlight=diag_embed#torch.diag_embed), [`diagflat`](https://pytorch.org/docs/stable/torch.html?highlight=diagflat#torch.diagflat), and [`diagonal`](https://pytorch.org/docs/stable/torch.html?highlight=diagonal#torch.diagonal).
~~This also introduces a new type/kind for signed dimensions:~~
```haskell
data Dim = PDim Nat | NDim Nat
```
~~This is useful for example in `diag_embed`, where you often want to the diagonal embedded in the last 2 dimensions (the PyTorch defaults are -2, -1). In retrospect I'm not sure it's a good idea to introduce this in this PR, since it will create some inconsistency with other functions that don't support signed dims yet. I'm happy to defer judgement on this and possibly …
=> Typed diagEmbed, diagflat, diagonal

.github/workflows/nix-macos.yml
Starting in Catalina, macOS runs a syspolicyd "assessment" that hits the network for each binary/script executable. It does cache these results, but Nix tends to introduce many "new" executables per build. (You can read more about this at https://github.com/NixOS/nix/issues/3789).
This PR adds a temporary, redundant macOS job with these assessments disabled. I'm hoping you can adopt it for a few weeks to help me collect more data on how this affects real projects.
=> add temp CI job to test syspolicy impact

examples/iris-classification/Main.hs, examples/iris-classification/README.md, examples/iris-classification/setup_data.sh, hasktorch/src/Torch/Data/CsvDataset.hs, hasktorch/src/Torch/Data/StreamedPipeline.hs, hasktorch/src/Torch/Functional.hs, hasktorch/src/Torch/Tensor.hs, hasktorch/test/Torch/Typed/OptimSpec.hs
=> Csv cleanup, Torch.Tensor fix

.github/workflows/stack-macos.yaml
This PR changes get-deps.sh to brew-install for macos.
When we use this, we do not have to set extra library settings like `DYLD_LIBRARY_PATH`.
=> Change get-deps.sh to brew-install

.gitmodules, deps/get-deps.sh
For stack's bug, hasktorch's repo can not be cloned on stack.
We already have the bug-fix on the master branch of stack, but I'm not sure when it will be released.
This PR stops the pytorch submodule and embeds the tag used in get-deps.sh.
=> Remove pytorch-repo

.github/workflows/nix-macos.yml
Reverts #422 
Thanks for your help testing this out. The results were a bit of a bust with respect to any short-term hope of speeding up macOS builds, but they did help me tease out the fact that the approach I used here doesn't actually disable the whole assessment--it seems to just keep the result of the assessment from being used.
With the approach used here ruled out, the only way I'm aware of to fully disable the assessments and reclaim the associated time requires a GUI to set up. :/
=> Revert "add temp CI job to test syspolicy impact"

hasktorch/src/Torch/Optim.hs, hasktorch/src/Torch/Typed/Optim.hs
PerformGC is executed every time in runStep.
performGC is blocking.(When it is non-moving-gc, performGC is not blocking.) It is useful to detect memory leaks.
=> Add performGC in runStep

nix/default.nix, shell.nix
Upgrades haskell-language-server to [0.4.0](https://github.com/haskell/haskell-language-server/releases/tag/0.4.0)
=> haskell-language-server: 0.3.0 -> 0.4.0

examples/examples.cabal, examples/optimizers-cpp-typed/Main.hs, examples/optimizers-cpp-typed/README.md, examples/optimizers-cpp-typed/TestFunctions.hs, hasktorch/hasktorch.cabal, hasktorch/src/Torch/Typed/Optim/CppOptim.hs
A typed version of Torch.Optim.CppOptim.  I have also added a partial reimplementation of the `optimizers-cpp` example under `optimizers-cpp-typed` to demonstrate usage.
=> Add Torch.Typed.Optim.CppOptim and associated example

libtorch-ffi/src/Torch/Internal/Managed/Type/Extra.hs, libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Extra.hs
`tensor.name` function of c++ returns `c10::ArrayRef<at::Dimname>`.
ArrayRef does not own Dimname, and tensor owns Dimname.
We have to copy `ArrayRef` to `std::vector<at: Dimname>`, but libtorch don't provide the copy-constructor.
Since the constructor cannot be generated automatically, this pr provides the copy-operation by handwritten code.
=> Add tensor_names function to get a list of at::Dimname from tensor

.github/workflows/stack-macos.yaml, stack-ghc88.yaml
To support ghc-810 for macos, we need to upgrade Cabal package of stack command.
https://github.com/haskell/cabal/issues/6421
Since it takes time to upgrade, we will continue to support ghc88 of macos for the time being.
=> Add stack-ghc88.yaml to keep supporting ghc-88

hasktorch/src/Torch/Autograd.hs, hasktorch/src/Torch/NN.hs, libtorch-ffi/src/Torch/Internal/Managed/Autograd.hs, libtorch-ffi/src/Torch/Internal/Unmanaged/Autograd.hs
Add a requires_grad argument to make a tensor of requires_grad=False, because running_mean argument of batchNorm function requires a tensor with requires_grad = False.
=> Add makeIndependent with requires_grad argument

libtorch-ffi/src/Torch/Internal/GC.hs
libtorch's c++ exception shows a following message.
This is a single line message, so it is hard to read it.
```
*** Exception: CppStdException "Exception: Trying to create tensor with negative dimension -1: [-1, 0]\nException raised from check_size_nonnegative at ../aten/src/ATen/native/TensorFactories.h:66 (most recent call first):\nframe #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f2e8a59bb89 in /lib/libc10.so)\nframe #1: <unknown function> + 0x1005253 (0x7f2e742cf253 in /lib/libtorch_cpu.so)\nframe #2: at::native::empty_cpu(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) + 0x173 (0x7f2e742cb783 in /lib/libtorch_cpu.so)\nframe #3: <unknown function> + 0x1331b0f …
```
=> Show c++ std-exception line by line.

hasktorch/src/Torch/Tensor.hs
When a tensor is not coutiguous, writePng of Torch.Vision outputs broken image.
writePng uses withTensor, and  it assumes that withTensor outputs contigous.
This pr fixes the situation.
=> Fix withTensor to use contiguous format

examples/rnn/Elman.hs, examples/rnn/GRU.hs, examples/rnn/LSTM.hs, hasktorch/src/Torch/NN.hs, hasktorch/src/Torch/Script.hs, hasktorch/src/Torch/Tensor.hs, hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs, hasktorch/src/Torch/Typed/Parameter.hs
This pr adds ToDevice typeclass to provide a general way to move the data from CPU to CUDA.
=> Add ToDevice typeclass for untyped api

hasktorch/hasktorch.cabal, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/src/Torch/Typed/Tensor.hs
Using `vecStack` instead of `stack` cut GHC memory usage and compile time by > 80% for my application.
=> Introduce alternative version of `stack` using `vector-sized`

hasktorch/src/Torch/Optim.hs, hasktorch/src/Torch/Optim/CppOptim.hs, hasktorch/src/Torch/Typed/Optim.hs, hasktorch/src/Torch/Typed/Optim/CppOptim.hs, libtorch-ffi/libtorch-ffi.cabal, libtorch-ffi/src/Torch/Internal/GC.hs
libtorch causes memory fragmentation.
It can be solved by using jemalloc, but it cannot be used in the nix environment, because ghc causes a segmentation fault. (See https://github.com/hasktorch/hasktorch/pull/513 )
https://news.ycombinator.com/item?id=24232809
According to this, calling malloc_trim after GC can eliminate fragmentation, and when I actually tried calling malloc_trim, it is effective.
=> Call mallocTrim after performGC

hasktorch/hasktorch.cabal, hasktorch/src/Torch/Typed/Aux.hs, hasktorch/src/Torch/Typed/Functional.hs
The 3.0 release of `singletons` split up into 3 packages so `Data.Singletons.Prelude` is now in `singletons-base`. I think this is the relevant [PR](https://github.com/goldfirere/singletons/pull/463).
This PR ~adds an upper bound to the hasktorch cabal file to fix for now~ removes the dependence on singletons, instead defining `Product` in `Torch.Typed.Aux`.
=> Remove dependency on singletons

examples/examples.cabal, examples/mnist-mixed-precision/Main.hs, examples/mnist-mixed-precision/README.md, examples/mnist-mixed-precision/setup-data.sh, examples/mnist-mlp/Main.hs, examples/mnist-mlp/README.md, examples/rnn/Elman.hs, examples/rnn/GRU.hs, examples/rnn/LSTM.hs, hasktorch/hasktorch.cabal, hasktorch/src/Torch/Autograd.hs, hasktorch/src/Torch/DType.hs, hasktorch/src/Torch/Functional.hs, hasktorch/src/Torch/Lens.hs, hasktorch/src/Torch/NN.hs, hasktorch/src/Torch/Script.hs, hasktorch/src/Torch/Tensor.hs, hasktorch/src/Torch/Typed/NN/Recurrent/LSTM.hs, hasktorch/test/LensSpec.hs, libtorch-ffi/src/Torch/Internal/Const.hs
This PR provides HasTypes typeclass for general dtype conversions.
This HasTypes typeclass is similar to HasTypes in generic-lens, but the behavior of this PR's HasTypes can be overridden simply by defining an instance. 
This PR hasn't changed Parameterized typeclass at all.  (It is  not trying to force a merge of Parameterized and GTravelable typeclass like https://github.com/hasktorch/hasktorch/pull/505.)
=> Add overwritable HasTypes to support generic dtype conversions

libtorch-ffi/src/Torch/Internal/Managed/Type/Tensor/Tensor0.hs, libtorch-ffi/src/Torch/Internal/Managed/Type/Tensor/Tensor1.hs, libtorch-ffi/src/Torch/Internal/Managed/Type/Tensor/Tensor2.hs, libtorch-ffi/src/Torch/Internal/Managed/Type/Tensor/Tensor3.hs, libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Tensor/Tensor0.hs, libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Tensor/Tensor1.hs, libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Tensor/Tensor2.hs, libtorch-ffi/src/Torch/Internal/Unmanaged/Type/Tensor/Tensor3.hs, spec/cppclass/tensor.yaml
Low level api does not have `rename` function of named-tensor.
This PR adds the function.
https://pytorch.org/docs/stable/named_tensor.html
The way to add the function is adhoc.
https://github.com/hasktorch/hasktorch/blob/master/spec/cppclass/gen.sh
I should stop using this `gen.sh` and use `Declarations.yaml`.
=> Add rename

hasktorch/hasktorch.cabal, hasktorch/src/Torch/Tensor.hs, hasktorch/src/Torch/Typed/Factories.hs, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/src/Torch/Typed/Lens.hs, hasktorch/src/Torch/Typed/Tensor.hs, hasktorch/test/Torch/Typed/NamedTensorSpec.hs
I implemented 3 different tensors to define named-tensor as follows.
- This PR with `Unnamed`-typeclass.
- https://github.com/hasktorch/hasktorch/pull/537
- https://github.com/hasktorch/hasktorch/pull/524
The method other than this PR is a lot of modification of the existing code.
When considering a way to gradually update an existing implementation to a new tensor (Named Tensor), it is better to put a layer that abstracts the `Unnamed Tensor` instead of modifying the definition of `Tensor` directly. 
So I'm making `Unnamed-typeclass` as the layer.
In addition to this, we can use multiple Tensor definitions by using that layer.
I'm thinking broadcast for the namedtensor.
=> Added named tensor

hie.yaml
[mnist-mixed-precision example](examples/mnist-mixed-precision) was missing from [hie.yaml](hie.yaml)
=> Add mnist-mixed-precision example to hie.yaml

hasktorch/hasktorch.cabal, hasktorch/src/Torch/Lens.hs, hasktorch/src/Torch/Tensor.hs, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/src/Torch/Typed/Lens.hs, hasktorch/src/Torch/Typed/NamedTensor.hs, hasktorch/src/Torch/Typed/Tensor.hs, hasktorch/test/Torch/Typed/NamedTensorSpec.hs
This PR improves the implementation of typed namedtensor.
The original functions of namedtensor are below.
http://nlp.seas.harvard.edu/NamedTensor
Some features have not been implemented yet.
The features of typed named tensors are below.
=> Add some features of typed namedtensor

nix/sources.json
This is related to https://github.com/hasktorch/tokenizers/pull/4.
libtorch-nix uses libcxx derivation. libcxx derivation is llvm's c++ library.
Normally we should use stdenv.cc.cc, so fix it.
=> Change libstdc++ to stdenv.cc.cc in libtorch-nix

examples/load-torchscript/Main.hs, hasktorch/src/Torch/Script.hs, hasktorch/test/ScriptSpec.hs
At first, this pr removes ScriptModule's forward function to avoid forward function collisions.
Then it adds the instance of HasForward for ScriptModule.
=> Add a HasForward instance of ScriptModule

.github/workflows/stack-linux.yml, hasktorch/.tintin.yml, hasktorch/doc/01-getting-started.md, hasktorch/doc/02-tensors.md, hasktorch/doc/02-walkthrough.md, hasktorch/doc/03-randomness.md, hasktorch/doc/04-automatic-differentiation.md, hasktorch/doc/05-differentiable-programs.md, hasktorch/doc/06-linear-regression.md, hasktorch/doc/07-typed-tensors.md, hasktorch/doc/index.md, hasktorch/hasktorch.cabal, hasktorch/src/Torch/Tutorial.hs, stack.yaml
Preview [here](https://htmlpreview.github.io/?https://github.com/hasktorch/hasktorch/blob/90518c5f96519448eba1ab287ba7d08f78226b5a/hasktorch/public/tutorial/index.html) (I'll keep this up-to-date for the PR and remove before merging).
To build & view the tintin docs (tested on NixOS):
```shell
mv stack-8.10.2.yaml stack.yaml
cd hasktorch
stack exec tintin -- run # should work(?) but broken for me (see below)
open .stack-work/tintin/rendered/index.html
```
Since `stack exec tintin -- run` didn't work for me, I instead did
```shell
stack install tintin
~/.local/bin/tintin run
```
=> Soft docs / tutorial using tintin

examples/vae/Main.hs, hasktorch/hasktorch.cabal, hasktorch/src/Torch.hs, hasktorch/src/Torch/Index.hs, hasktorch/src/Torch/Tensor.hs, hasktorch/src/Torch/Tutorial.hs, hasktorch/test/IndexSpec.hs
This PR adds the slice operator of python-style with ~~`pySlice`~~ `slice` quote.
When you get values in python looks like this,
```python
tensor[0,0:3]
```
hasktorch uses ~~pySlice~~ slice to get the value with `!`  and ~~`pySlice`~~ `slice` as follows:
```
tensor ! [slice|0,0:3|]
```
=> Add python-style slice operator

examples/examples.cabal, hasktorch/hasktorch.cabal
Mainly for attribution on the tutorial page https://hasktorch.github.io/tutorial/index.html
=> updated authors to `hasktorch contributor team` instead of `austin huang`

hasktorch/src/Torch/Index.hs, hasktorch/src/Torch/Tensor.hs, hasktorch/test/IndexSpec.hs
To convert index into lens, add lslice function of template haskell.
For example, you can write getter and setter for tensor as follows.
These are the odd element accessors of the tensor.
```haskell
-- getter 
tensor ^. [lslice|1::2|]
-- setter
tensor & [lslice|1::2|] .~ 2
```
=> Add lens for index

experimental/gradually-typed/doctests.hs, experimental/gradually-typed/hasktorch-gradually-typed.cabal, experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Dropout.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Stack.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/Shape/Class.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations/Reduction.hs, experimental/gradually-typed/test/TensorSpec.hs, libtorch-ffi/src/Torch/Internal/GC.hs
TODO:
EDIT: This looks like a bug in GHC: https://gitlab.haskell.org/ghc/ghc/-/issues/13775
=> Add `all`, `any` reduction functions

hasktorch/src/Torch/Functional.hs, hasktorch/src/Torch/NN.hs, hasktorch/src/Torch/Typed/Functional.hs, hasktorch/src/Torch/Typed/NN/Convolution.hs, hasktorch/test/FunctionalSpec.hs
Typed and Untyped convolution and transposed convolution functions and layers. Specs added in Untyped to match the existing conv2d test. Would like to add a Torch.GraduallyTyped.NN.Convolution, but I haven't looked into or worked with GraduallyTyped more than in passing. Typed and Untyped seem to behave and test as expected so far which makes sense given they were an expansion built off of existing scaffolding. 
Also includes `InstanceNorm`. I followed the convention set by `BatchNorm` of not having any Parameterized instance, but I could see it being helpful to have one for working with full models that use the layers, especially with serialization and deserialization. 
Hope this all looks good, and I'd be glad for any feedback or suggestions!
=> Expose in Functional and add layers for all conv-nd and convTranspose-nd 

experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Class.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Normalization.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Sparse.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/Type.hs, experimental/gradually-typed/test/TensorSpec.hs, experimental/gradually-typed/test/TransformerSpec.hs
I had to comment the `TensorLike` instance for `Tensor`, because it would allow for switching gradients off or on from outside of `IO` which mustn't be allowed.
=> Fix to cuda tensor

.github/workflows/cabal-linux.yml, .github/workflows/cabal-macos.yaml, .github/workflows/stack-linux.yml, .github/workflows/stack-macos.yaml, .github/workflows/stack-nix-linux.yml, Dockerfile, deps/get-deps.sh, experimental/gradually-typed/hasktorch-gradually-typed.cabal, experimental/gradually-typed/src/Torch/Data/Parser.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/Internal/Vector.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Class.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GStack.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/IndexingSlicingJoining.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations/BlasLapack.hs, experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/Type.hs, setenv, setup-cabal.sh, stack.yaml
This is to use gradually typed api in workflows other than nix.
I update get-deps.sh to install the shared library of libtokenizers_haskell.
=> To build gradually typed api, install the binary of libtokenizers

.github/workflows/nix-haddock-linux.yml, .github/workflows/nix-jupyterlab.yml, .github/workflows/nix-linux-cu10.yml, .github/workflows/nix-linux-cu11.yml, .github/workflows/nix-linux.yml, .github/workflows/nix-macos.yml, .github/workflows/setup-iohk-cache.sh, .github/workflows/stack-nix-linux.yml, README.md, setup-iohk-cache.sh
To use cached ghc of IOHK, update substituters of nix.
https://input-output-hk.github.io/haskell.nix/tutorials/getting-started/
Both cachix and hydra are set in the plutus-community documentation, so both are set in the same way.
https://docs.plutus-community.com/docs/setup/Ubuntu.html
=> Fix IOHK's cache

.github/workflows/cabal-linux.yml
The files of github-releases become having short time token with redirect url.
Current apt of linux does not work with github-releases, because the query string of the redirect URL is processed incorrectly.
We've decided to put the assets on our instance from github-releases.
The files of instance are cached in cloudflare.
=> Change the apt source of libtorch to apt-hasktorch.com with cloudflare

.github/workflows/nix-haddock-linux.yml, .github/workflows/nix-linux-cu10.yml, .github/workflows/nix-linux-cu11.yml, .github/workflows/nix-linux.yml, .github/workflows/nix-macos.yml, .github/workflows/stack-nix-linux.yml, flake.nix
It seems that nix-flake only searches substituters in flake.nix.
=> Add cache.nixos.org to substituters

hasktorch/hasktorch.cabal, hasktorch/src/Torch/DType.hs, hasktorch/src/Torch/Tensor.hs, hasktorch/test/TensorSpec.hs
Add TensorLike instances for complex numbers to read and write them.
```
ghci> :m + Data.Complex
ghci> a = [1,2,3] :: [Complex Double]
ghci> b = asTensor a
ghci> b * b
Tensor ComplexDouble [3] [ 1.0000   ,  4.0000   ,  9.0000   ]
ghci> b + b
Tensor ComplexDouble [3] [ 2.0000   ,  4.0000   ,  6.0000   ]
ghci> b / b
Tensor ComplexDouble [3] [ 1.0000   ,  1.0000   ,  1.0000   ]
ghci> b - b
Tensor ComplexDouble [3] [ 0.0000,  0.0000,  0.0000]
ghci> a = [1 :+ 1 , 2:+2,3:+3] :: [Complex Double]
ghci> b = asTensor a
ghci> b
Tensor ComplexDouble [3] [Cannot show stacktrace
Exception: value cannot be converted to type double without overflow: (1,1); type: std::runtime_error
Cannot show stacktrace
Exception: value cannot be converted to type double without overflow: (1,1); type: std::runtime_error …
```
=> Add instances of complex numbers

hasktorch/src/Torch/Autograd.hs, hasktorch/src/Torch/Optim/CppOptim.hs, hasktorch/src/Torch/Typed/Optim/CppOptim.hs, libtorch-ffi/src/Torch/Internal/Managed/Optim.hs, libtorch-ffi/src/Torch/Internal/Unmanaged/Optim.hs
https://github.com/hasktorch/hasktorch/issues/639
In case of CUDA, requies-grad-property of `unsafeStep`'s parameters is deleted.
We can avoid this problem by using the parameters set in the optimizer at initialization as they are, so delete the list of parameters from `unsafeStep` function.
=> Fix c++-optimizer to converge loss with CUDA

README.md
nix-shell is not supported, so fix the README.
https://github.com/hasktorch/hasktorch/issues/641
=> Fix README to use not 'nix-shell' but 'nix develop'

.github/workflows/cabal-linux.yml, .github/workflows/cabal-macos.yaml, .github/workflows/nix-haddock-linux.yml, .github/workflows/nix-linux-cu10.yml, .github/workflows/nix-linux-cu11.yml, .github/workflows/nix-linux.yml, .github/workflows/nix-macos.yml, .github/workflows/stack-macos.yaml, flake.lock, flake.nix, hasktorch/test/ScriptSpec.hs, libtorch-ffi/src/Torch/Internal/GC.hs, nix/haskell.nix, nix/libtorch-binary-hashes.nix, nix/libtorch.nix, nix/stack-shell.nix, setup-cabal.sh, stack.yaml
The ghc and lts we are using are a little old.
We can not resolve package dependencies in macos,  so upgrade them.
=> Bump ghc to 9.0.2

hasktorch/src/Torch/Functional.hs, hasktorch/src/Torch/NN.hs, hasktorch/src/Torch/Tensor.hs
batchNorm is not  a pure function.
It updates the argument of runningMean and runningVar.
This PR changes batchNorm from a pure function to an impure function.
=> Fix batchNorm from pure-function to impure-function

.github/workflows/nix-haddock-linux.yml, .github/workflows/nix-linux-cu10.yml, .github/workflows/nix-linux-cu11.yml, .github/workflows/nix-linux.yml, .github/workflows/stack-nix-linux.yml, nix/haskell.nix, nix/libtorch.nix, nix/stack-shell.nix, shell.nix
libtorch needs two include paths (/usr/include/torch and /usr/include/torch/csrc/api/include/).
So users need to add the extra-include-dirs of /usr/include/torch/csrc/api/include/. 
This PR adds symlinks of /usr/include/torch/csrc/api/include/* to /usr/include/ not to add the extra-include-dirs.
=> Add symlinks of libtorch not to add extra-include-dirs

deps/get-wheel.sh, hasktorch/test/FunctionalSpec.hs
When macOS, hasktorch's test fails, because lstsq does not allow zero matrix as an argument.
This PR fixes the error.
=> Fix the test of lstsq, because it does not allow zero as A.

hasktorch/src/Torch/Tensor.hs
Bug: Exception: index_select(): Expected dtype int32 or int64 for index
Solution: Do not convert Tensor using `asTensor' indexList t`, as this would convert the type of `indexList` to the type of `t`. Rather use `asTensor indexList`. Another approach would be `asTensor' indexList int64_opts`, which would however always perform a transformation to `int64`.
=> indexSelect' must use an Int64/32 tensor for indices

examples/autograd/Main.hs, examples/autograd/README.md, examples/autograd/nn.svg
Reading through the example `autograd`, I found it helpful to have a picture of the NN before me.
I generated one at https://alexlenail.me/NN-SVG/
Commits:
- examples/autograd: Whitespace changes
- examples/autograd/README: fix a typo; correct level of subheadings
- examples/autograd/README: add a visualization (SVG) of the NN
=> Add a picture of the NN to `examples/autograd/`

.github/workflows/cabal-linux.yml, .github/workflows/cabal-macos.yaml, .github/workflows/nix-haddock-linux.yml, .github/workflows/nix-linux-cu10.yml, .github/workflows/nix-linux-cu11.yml, .github/workflows/nix-linux.yml, .github/workflows/stack-linux.yml, .github/workflows/stack-macos.yaml, .github/workflows/stack-nix-linux.yml
- CI: bump actions/checkout to v4 and actions/cache to v3 (latest versions)
This will silence a deprecation warning for node 12 when running the CI.
- CI: bump GHC from 9.2.4 to 9.2.8
This follows a previous commit bumping to LTS 20.26 (which is GHC 9.2.8).
- CI: cosmetics: removed unused "id: cache-stack"
=> CI: bump to latest `actions/checkout` and `actions/cache`; bump GHC to 9.2.8

.github/workflows/cabal-linux.yml, .github/workflows/cabal-macos.yaml, .github/workflows/stack-linux.yml, .github/workflows/stack-macos.yaml, .github/workflows/stack-nix-linux.yml
This PR makes some cosmetic simplifications on the workflows.
- CI: setup submodules with actions/checkout
- CI: Stack is preinstalled on the GHA runners, no need to install it
- CI: GHCup is preinstalled on the GHA runners, no need to install it
I have some more ideas for CI cosmetics, like removing redundant instructions or steps. Let me know whether such work is welcome in general or whether this would conflict with some principles behind the CI setup.
So far, I commented out redundant installation steps, let me know whether you prefer that I fully delete them.
=> CI: some workflow simplifications

.github/workflows/cabal-linux.yml, .github/workflows/cabal-macos.yaml
This commit restructures the workflows `cabal-linux` and `cabal-macos`.
Caching
-------
1. Only cache dependencies.
From looking into PR runs I deduced that `cabal` hardly reuses anything from `dist-newstyle`.
Thus, this local build directory is dropped from the cache, only the global `~/.cabal/store` is now cached.
This dramatically reduces the cache sizes (here with GHC 9.2.8):
| cabal  | linux  | macos  |
|--------|--------|--------|
| before | 450 MB | 250 MB |
| after  |  85 MB | 100 MB |
2. Save dependency cache early.
Splitting `actions/cache` into `/restore` and `/save` step,
we can immediately cache the dependencies after they have been build.
So they will be preserved even if later the building of `hasktorch` or some test fails.
This will speed up the next attempt, because …
=> CI #684: revise caching for the cabal workflows

libtorch-ffi/csrc/hasktorch_finializer.cpp, libtorch-ffi/csrc/hasktorch_finializer.h
libtorch-ffi's haskell codes have delete_tensortensorint64int64tensortensor.
However libtorch-ffi's c codes do not have delete_tensortensorint64int64tensortensor.
This PR fixes the missing symbol.
```
$ git grep -h 'finalizer.h delete.*' libtorch-ffi -e 's/.*\(delete.*\)"/\1/g' | sort |uniq  > delete_symbols.txt
$ git grep -h 'finalizer.h delete.*' libtorch-ffi/src | sed -e 's/.*\(delete.*\)"/\1/g' | sort |uniq  > haskell.txt
$ git grep -h 'delete.*' libtorch-ffi/csrc/hasktorch_finializer.h | sed -e 's/.* \(delete_.*\)(.*/\1/g' |sort | uniq > csrc.txt
$ diff haskell.txt csrc.txt
46d45
< delete_tensortensorint64int64tensortensor
51a51
> delete_tensortensortensortensorint64int64int64int64tensor
53a54,55
> delete_tensortensortensortensortensortensor
> …
```
=> Fix: Missing delete_tensortensorint64int64tensortensor in csrc

.mailmap, cabal.project, codegen/codegen.cabal, hasktorch/hasktorch.cabal, libtorch-ffi/libtorch-ffi.cabal
- **Drop redundant constraints**
- **Fix synopsis**
- **Fork of union-find-array is obsolete**
=> Remove redundant constraints in .cabal files, drop fork of union-find-array

README.md, examples/mnist-mixed-precision/Main.hs, examples/mnist-mlp/Main.hs, examples/static-mnist-cnn/Main.hs, examples/static-mnist-mlp/Main.hs, examples/static-mnist/Common.hs, nix/datasets.nix
* Added CLI arguments to MNIST examples
* Added nix derivation for mnist datasets
These changes were added to accommodate the changes being made in #700. Since the nix store is read only and we don't want to ship mnist with hasktorch, it makes more sense to have CLI arguments to the mnist examples.
=> Added CLI arguments to MNIST examples

libtorch-ffi/Setup.hs, libtorch-ffi/libtorch-ffi.cabal
- Respect LIBTORCH_HOME or fall back to XDG cache (~/.cache/libtorch/<ver>/<platform>/<flavor>)
- Key cache by version, platform, and CUDA flavor
- Add idempotence marker to avoid re-downloads
- Inject extra include/lib dirs from global cache during confHook
- Keep LIBTORCH_SKIP_DOWNLOAD to bypass network
Fixes #740
=> build: cache libtorch globally and wire paths via confHook
